In [ ]:
import numpy as np

In [ ]:
x = [21, 23, 27, 32, 34, 41, 50, 53, 57, 59, 38, 46, 46, 48, 60] # idade dos funcionários
y = [1000, 1100, 1250, 1700, 1500, 1980, 2500, 3500, 2200, 4100, 3900, 5100, 5500, 7000, 6500] # salário dos funcionários

In [ ]:
import plotly.express as px

In [ ]:
grafico = px.scatter(x=x, y=y)
grafico.show()

In [ ]:
base_salario = np.array([[21,1000], [23,1100], [27,1250], [32,1700], [34,1500], 
                         [41,1980], [38,3900], [46,5100], [46,5500], [48,7000],
                         [53,3500], [57,2200], [59,4100], [60,6500], [50,2500]])

In [ ]:
base_salario

array([[  21, 1000],
       [  23, 1100],
       [  27, 1250],
       [  32, 1700],
       [  34, 1500],
       [  41, 1980],
       [  38, 3900],
       [  46, 5100],
       [  46, 5500],
       [  48, 7000],
       [  53, 3500],
       [  57, 2200],
       [  59, 4100],
       [  60, 6500],
       [  50, 2500]])

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
# normalização da escala dos dados

scaler_salario = StandardScaler()
base_salario = scaler_salario.fit_transform(base_salario)

In [ ]:
base_salario

array([[-1.72382169, -1.15955852],
       [-1.56221341, -1.10814445],
       [-1.23899684, -1.03102336],
       [-0.83497613, -0.79966007],
       [-0.67336785, -0.9024882 ],
       [-0.10773886, -0.65570069],
       [-0.35015128,  0.33144933],
       [ 0.29628185,  0.9484181 ],
       [ 0.29628185,  1.15407435],
       [ 0.45789014,  1.92528531],
       [ 0.86191085,  0.12579308],
       [ 1.18512741, -0.54258975],
       [ 1.3467357 ,  0.43427746],
       [ 1.42753984,  1.66821499],
       [ 0.61949842, -0.38834756]])

In [ ]:
from sklearn.cluster import KMeans

In [ ]:
# processo de treinamento do modelo

kmeans_salario = KMeans(n_clusters=3)
kmeans_salario.fit(base_salario)

KMeans(n_clusters=3)

In [ ]:
centroide = kmeans_salario.cluster_centers_
centroide

array([[ 0.44172931, -0.22587912],
       [ 0.76494588,  1.22605404],
       [-1.20667519, -1.00017492]])

In [ ]:
scaler_salario.inverse_transform(centroide) # desnormalização dos dados

array([[  47.8, 2816. ],
       [  51.8, 5640. ],
       [  27.4, 1310. ]])

In [ ]:
rotulos = kmeans_salario.labels_
rotulos

array([2, 2, 2, 2, 2, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0], dtype=int32)

In [ ]:
grafico_rotulos = px.scatter(x=base_salario[:,0], y=base_salario[:,1], color=rotulos)
grafico_rotulos.show()

In [ ]:
grafico_centroide = px.scatter(x=centroide[:,0], y=centroide[:,1], size=[8,8,8])
grafico_centroide.show()

In [ ]:
import plotly.graph_objects as go

grafico_juncao = go.Figure(data=grafico_rotulos.data + grafico_centroide.data)
grafico_juncao.show()