In [1]:
import numpy as np

## Comparações (operações elemento a elemento)

In [9]:
# criação dos arrays 
x = np.array([[1,2], [3,4]])
y = np.array([1.5, 3.5])

print('x:\n', x)
print('y:\n', y)

x:
 [[1 2]
 [3 4]]
y:
 [1.5 3.5]


In [10]:
# comparações ponto a ponto
print('Comparação de um array com escalar (>):\n', x > 2)
print('\nComparação de um array com escalar (>=):\n', x >= 2)
print('\nComparação de um array com escalar (<):\n', x < 2)
print('\nComparação de um array com escalar (<=):\n', x <= 2)

# comparações broadcasting
print('\nComparação entre arrays (==):\n', x == y)
print('\nComparação entre arrays (>):\n', x > y)
print('\nComparação entre arrays (<):\n', x < y)

Comparação de um array com escalar (>):
 [[False False]
 [ True  True]]

Comparação de um array com escalar (>=):
 [[False  True]
 [ True  True]]

Comparação de um array com escalar (<):
 [[ True False]
 [False False]]

Comparação de um array com escalar (<=):
 [[ True  True]
 [False False]]

Comparação entre arrays (==):
 [[False False]
 [False False]]

Comparação entre arrays (>):
 [[False False]
 [ True  True]]

Comparação entre arrays (<):
 [[ True  True]
 [False False]]


## Indexação booleana (operações de filtro)

In [12]:
# criação de mu array

x = np.array([[1, 3, 7],
              [4, 11, 21],
              [42, 8, 9]])
print('x:\n', x)

x:
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]


In [15]:
# Retornar o número de elementos maiores que k

k = 10
cond = x > k
print('condição:\n', cond)
print(f'\nelementos maiores que {k}:', x[cond])
print(f'\nnúmero de elementos maiores que {k}:', len(x[cond]))

condição:
 [[False False False]
 [False  True  True]
 [ True False False]]

elementos maiores que 10: [11 21 42]

número de elementos maiores que 10: 3


In [16]:
# extração de números pares

cond = x % 2 == 0
print('condição:\n', cond)
print('\nnúmeros pares:', x[cond])

condição:
 [[False False False]
 [ True False False]
 [ True  True False]]

números pares: [ 4 42  8]


In [21]:
# extração de números ímpares

cond = x % 2 == 1
print('condição:\n', cond)
print('\nnúmeros ímpares:', x[cond])

condição:
 [[ True  True  True]
 [False  True  True]
 [False False  True]]

números ímpares: [ 1  3  7 11 21  9]
