In [1]:
# importando as bibliotecas
import numpy as np

In [ ]:
help(np.array)
np.array?

## Criação de arrays

In [10]:
# Criação de array 1D: [1, 2, 3]
l = [1, 2, 3]
x = np.array(l)
print('x:', x)
print('shape:', x.shape) 

x: [1 2 3]
shape: (3,)


In [11]:
type(x)

numpy.ndarray

In [12]:
# Criação de array 2D: [[1, 2], [3, 4]] (Listas aninhadas)
dim = [[1, 2], [3, 4]]
y = np.array(dim)
print('y:', y)
print('shape:', y.shape) 

y: [[1 2]
 [3 4]]
shape: (2, 2)


Operações com numpy

In [27]:
# Array contendo apenas zeros (0's)
# zeros(shape, dtype=float, order='C', *, like=None)

sp = (3, 3) # (linhas, colunas)
z = np.zeros(sp, dtype=int)
print('y:', z)
print('shape:', z.shape) 

y: [[0 0 0]
 [0 0 0]
 [0 0 0]]
shape: (3, 3)


In [ ]:
help(np.zeros)

In [28]:
# Array contendo apenas ums (1's)
# ones(shape, dtype=None, order='C', *, like=None)

sp = (2, 3) # (linhas, colunas)
z = np.ones(sp, dtype=int)
print('y:', z)
print('shape:', z.shape) 

y: [[1 1 1]
 [1 1 1]]
shape: (2, 3)


In [ ]:
help(np.ones)

In [41]:
# crray com valores dentro de um intervalo com distância entre eles igualmente espaçadas
# linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

# valores uniformemente espaçados entre 5 e 15
x_min, x_max = 5, 15
ls = np.linspace(start=x_min, stop=x_max, num=6)
print('ls:', ls)
print('shape:', ls.shape) 

ls: [ 5.  7.  9. 11. 13. 15.]
shape: (6,)


In [ ]:
help(np.linspace)

In [46]:
# Criação de matriz identidade: Array diagonal composta apenas por 1's e demais elementos compostos por 0's
# eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)

n = 4
mi = np.eye(n)
print('mi:', mi)
print('shape:', mi.shape) 

mi: [[1. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]]
shape: (4, 2)


In [ ]:
help(np.eye)

In [65]:
# Array de valores aleatórios entre 0 e 1
# random(size=None)

rd = np.random.random(size=(3, 2))
print('rd:\n', rd)
print('shape rd:', rd.shape) 

print() 

rd2 = np.random.random(5)
print('rd2:', rd2)
print('shape rd2:', rd2.shape) 

rd:
 [[0.06963695 0.8937487 ]
 [0.88527151 0.02741634]
 [0.40685665 0.82308573]]
shape rd: (3, 2)

rd2: [0.12560391 0.4653345  0.32559786 0.62548259 0.22649702]
shape rd2: (5,)


In [ ]:
help(np.random.random)