In [1]:
import numpy as np

## Operações úteis com Numpy

In [3]:
# array

x = np.array([[1, 3, 7],
              [4, 11, 21],
              [42, 8, 9]])
print('x:\n', x)

x:
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]


In [12]:
# reshape: transformar uma matriz em um vetor coluna
# 3x3 vira (9, 1) => 3 * 3 = 9 * 1 = 9

print('Transformação de vetor coluna:', x.reshape((9, 1)))

# reshape: transformar uma matriz em um vetor linha
# 3x3 vira (1, 9) => 3 * 3 = 1 * 9 = 9

print('\nTransformação de vetor linha:', x.reshape((1, 9)))

Transformação de vetor coluna: [[ 1]
 [ 3]
 [ 7]
 [ 4]
 [11]
 [21]
 [42]
 [ 8]
 [ 9]]

Transformação de vetor linha: [[ 1  3  7  4 11 21 42  8  9]]


In [10]:
# Transposição da matrix

print('transporta:\n', x.T)

transporta:
 [[ 1  4 42]
 [ 3 11  8]
 [ 7 21  9]]


In [53]:
# npm.sum: Soma dos elementos de uma determinado eixo, axis = { linha: 0, coluna: 1 }
print('x:\n', x)
print('\nSoma de todos os elementos de x:', np.sum(x)) # soma de todos os elementos da matriz
print('\nSoma dos elementos de x no eixo y (coluna a coluna, axis=0):', np.sum(x, axis=0)) # soma de todos os elementos do axis 0
print('\nSoma dos elementos de x no eixo x (linha a linha, axis=1):', np.sum(x, axis=1)) # soma de todos os elementos do axis 1

x:
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]

Soma de todos os elementos de x: 106

Soma dos elementos de x no eixo y (coluna a coluna, axis=0): [47 22 37]

Soma dos elementos de x no eixo x (linha a linha, axis=1): [11 36 59]


In [54]:
# npm.mean: Média dos elementos de uma determinado eixo, axis = { linha: 0, coluna: 1 }
print('x:\n', x)
print('\nMédia de todos os elementos de x:', np.mean(x)) # Média de todos os elementos da matriz
print('\nMédia dos elementos de x no eixo y (coluna a coluna, axis=0):', np.mean(x, axis=0)) # Média de todos os elementos do axis 0
print('\nMédia dos elementos de x no eixo x (linha a linha, axis=1):', np.mean(x, axis=1)) # Média de todos os elementos do axis 1

x:
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]

Média de todos os elementos de x: 11.777777777777779

Média dos elementos de x no eixo y (coluna a coluna, axis=0): [15.66666667  7.33333333 12.33333333]

Média dos elementos de x no eixo x (linha a linha, axis=1): [ 3.66666667 12.         19.66666667]


In [55]:
# npm.median: Mediana dos elementos de uma determinado eixo, axis = { linha: 0, coluna: 1 }
print('x:\n', x)
print('\nMediana de todos os elementos de x:', np.median(x)) # Mediana de todos os elementos da matriz
print('\nMediana dos elementos de x no eixo y (coluna a coluna, axis=0):', np.median(x, axis=0)) # Mediana de todos os elementos do axis 0
print('\nMediana dos elementos de x no eixo x (linha a linha, axis=1):', np.median(x, axis=1)) # Mediana de todos os elementos do axis 1

x:
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]

Mediana de todos os elementos de x: 8.0

Mediana dos elementos de x no eixo y (coluna a coluna, axis=0): [4. 8. 9.]

Mediana dos elementos de x no eixo x (linha a linha, axis=1): [ 3. 11.  9.]


In [34]:
# npm.where: índice da posição do elemento onde determinada condição é atendida
cond = x % 2 == 0
print('Condição:\n', cond) 
print('\nElementos da condição:', x[cond]) 
i, j = np.where(cond) # indices [i, j] == x[cond]
print('\níndice i (linhas):', i)
print('\níndice j (colunas):', j)

print(x[i[0]][j[0]] == x[cond][0])
print(x[i[1]][j[1]] == x[cond][1])
print(x[i[2]][j[2]] == x[cond][2])

Condição:
 [[False False False]
 [ True False False]
 [ True  True False]]

Elementos da condição: [ 4 42  8]

índice i (linhas): [1 2 2]

índice j (colunas): [0 0 1]
True
True
True


In [52]:
# indexação booleana e slicing: Selecionar as linhas de x que possuam algum número par

print('x:\n', x)

cond = x % 2 == 0
print('\nCondição:\n', cond) 
print('\nElementos da condição:', x[cond]) 

# se houver alguma condição True na linha, a soma será > 0
# soma dos elementos booleanos = [[False False False][ True False False][ True  True False]] == [[0, 0, 0], [1, 0, 0], [1, 1, 0]] => [0, 1, 2]
i_row = np.where(np.sum(cond, axis=1))[0]
print('\níndices das linhas que possuem números pares:', i_row)
print('\nlinhas que possuem números pares:\n', x[i_row, :])

# se houver alguma condição True na coluna, a soma será > 0
# soma dos elementos booleanos = [[False False False][ True False False][ True  True False]] == [[0, 0, 0], [1, 0, 0], [1, 1, 0]] => [0, 1]
i_col = np.where(np.sum(cond, axis=0))[0]
print('\ncolunas que possuem números pares:\n', x[:, i_col])

x:
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]

Condição:
 [[False False False]
 [ True False False]
 [ True  True False]]

Elementos da condição: [ 4 42  8]

índices das linhas que possuem números pares: [1 2]

linhas que possuem números pares:
 [[ 4 11 21]
 [42  8  9]]

colunas que possuem números pares:
 [[ 1  3]
 [ 4 11]
 [42  8]]
