In [1]:
# importando as bibliotecas
import numpy as np

## Indexação de arrays

In [5]:
# os índices no Python vão de 0 a n-1, onde n é o tamanho da dimensão

x = np.linspace(start=10, stop=100, num=10, dtype=int)
print('x:', x)
print('shape:', x.shape)

x: [ 10  20  30  40  50  60  70  80  90 100]
shape: (10,)


In [13]:
# extração de elementos
print(x[0]) # primeiro elemento
print(x[-1]) # último elemento

10
100


In [43]:
# slicing: extração de subarrays
print(x[0:2]) # subarray com os elementos de indice 0 à 2-1 ou 0 à 1
print(x[0:5]) # subarray com os elementos de indice 0 à 5-1 ou 0 à 4
print(x[3:5]) # subarray com os elementos de indice 3 à 5-1 ou 3 à 4
print()

# slicing com omissão
print(x[0:-1]) # subarray sem último elemento
print(x[:-1]) # A omissão do primeiro elemento equivale à 0
print()
print(x[4:10]) # subarray com os elementos de indice 4 à 10-1 ou 4 à 9
print(x[4:]) # A omissão do segundo elemento equivale ao tamanho da dimensão (n elementos)

[10 20]
[10 20 30 40 50]
[40 50]

[10 20 30 40 50 60 70 80 90]
[10 20 30 40 50 60 70 80 90]

[ 50  60  70  80  90 100]
[ 50  60  70  80  90 100]


In [50]:
# slicing em array 2D
y = x.reshape(2, 5) # reshape de x para 2 linhas e 5 colunas
print('y:', y)

y: [[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [52]:
# extração de elementos
print(y[0, 0]) # primeira linha, primeira coluna
print(y[-1, -1]) # última linha, última coluna
print(y[0, -1]) # primeira linha, última coluna
print(y[-1, 0]) # última linha, primeira coluna

10
100
50
60


In [96]:
# slicing: extração de subarrays [slicing linear, slicing colunar]
# slicing linear: quantas linhas serão pegas
# slicing colunar: quantas colunas serão pegas

print('y:\n',y) 

print('\n',y[0:0, 0:0]) # subarray com nenhuma linha (já ignora o slicing da coluna)
print('\n', y[0:1, 0:-1]) # subarray com as linhas de indice 0 a 1-1 OU 0 à 0 / colunas sem os últimos elementos
print('\n', y[0:2, 3:5]) # subarray com as linhas de indice 0 à 2-1 ou 0 à 1 / com as colunas de indice 3 à 5-1 ou 3 à 4

print('\nslicing com omissão')
# A omissão do primeiro elemento equivale à 0
# A omissão do segundo elemento equivale ao tamanho da dimensão (n elementos)

print('\n', y[:0, :]) # subarray com nenhuma linha (já ignora o slicing da coluna)
print('\n', y[0, :]) # primeira linha inteira
print('\n', y[-1, :]) # última linha inteira
print('\n', y[:, [-1]]) # última coluna inteira

# y[0:2, 3:5] == y[0:, 3:] == y[:, 3:]
print('\n', y[0:, 3:]) # subarray com as linhas de indice 0 à 2-1 ou 0 à 1 / com as colunas de indice 3 à 5-1 ou 3 à 4
print('\n', y[:, 3:]) # subarray com as linhas de indice 0 à 2-1 ou 0 à 1 / com as colunas de indice 3 à 5-1 ou 3 à 4

y:
 [[ 10  20  30  40  50]
 [ 60  70  80  90 100]]

 []

 [[10 20 30 40]]

 [[ 40  50]
 [ 90 100]]

slicing com omissão

 []

 [10 20 30 40 50]

 [ 60  70  80  90 100]

 [[ 50]
 [100]]

 [[ 40  50]
 [ 90 100]]

 [[ 40  50]
 [ 90 100]]


In [101]:
# ATENÇÃO: Os elementos alterados no slicing alteram também o array original
# slicing é um compartilhamento de memória do array original

a = np.array([1, 2, 3])
n = a[:2]

print('a:',a)
print('n:',n)

n[0] = 10

# Alteração do valor de n altera o valor de a
print('\na:',a)
print('n:',n)

a: [1 2 3]
n: [1 2]

a: [10  2  3]
n: [10  2]


In [103]:
# Correção para o compartilhamento de memória

a = np.array([1, 2, 3])
n = a[:2].copy() # Cria-se uma cópia do slicing para o array n

print('a:',a)
print('n:',n)

n[0] = 10

print('\na:',a)
print('n:',n)

a: [1 2 3]
n: [1 2]

a: [1 2 3]
n: [10  2]
